/**
 * e-community-local
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package at.fhooe.ecommunity.data.remote.openapi.local.models

import at.fhooe.ecommunity.data.remote.openapi.local.models.SmartMeterDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param memberId 
 * @param isConnectedToInternet 
 * @param isWiredConnected 
 * @param wifiSSID 
 * @param smartMeter 
 */

data class StatusDto (

    @Json(name = "memberId")
    val memberId: java.util.UUID? = null,

    @Json(name = "isConnectedToInternet")
    val isConnectedToInternet: kotlin.Boolean? = null,

    @Json(name = "isWiredConnected")
    val isWiredConnected: kotlin.Boolean? = null,

    @Json(name = "wifiSSID")
    val wifiSSID: kotlin.String? = null,

    @Json(name = "smartMeter")
    val smartMeter: SmartMeterDto? = null

)

