/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param baseRate 
 * @param workingPricePlus 
 * @param taxRate 
 * @param gridLevel 
 */

data class LocalGridPriceRateDto (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "baseRate")
    val baseRate: kotlin.Double? = null,

    @Json(name = "workingPricePlus")
    val workingPricePlus: kotlin.Double? = null,

    @Json(name = "taxRate")
    val taxRate: kotlin.Double? = null,

    @Json(name = "gridLevel")
    val gridLevel: kotlin.Int? = null

)

