/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.SupplyMode

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param streetNr 
 * @param zipCode 
 * @param cityName 
 * @param countryCode 
 * @param gridLevel 
 * @param supplyMode 
 */

data class LocalMemberDto (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "streetNr")
    val streetNr: kotlin.String? = null,

    @Json(name = "zipCode")
    val zipCode: kotlin.String? = null,

    @Json(name = "cityName")
    val cityName: kotlin.String? = null,

    @Json(name = "countryCode")
    val countryCode: kotlin.String? = null,

    @Json(name = "gridLevel")
    val gridLevel: kotlin.Int? = null,

    @Json(name = "supplyMode")
    val supplyMode: SupplyMode? = null

)

