/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param memberId 
 * @param newPassword 
 * @param resetToken 
 */

data class ResetPasswordModel (

    @Json(name = "memberId")
    val memberId: java.util.UUID,

    @Json(name = "newPassword")
    val newPassword: kotlin.String,

    @Json(name = "resetToken")
    val resetToken: kotlin.String

)

