package at.fhooe.ecommunity.ui.screen.sharing.models

enum class ContractState {
    CONTRACT_CREATED,
    CONTRACT_PENDING,
    CONTRACT_ACTIVE,
    CONTRACT_ACTIVE_WITHDRAW_READY,
    CONTRACT_PAYMENT_PENDING,
    CONTRACT_REJECTED,
    CONTRACT_REVOKED,
    CONTRACT_CLOSED,
    CONTRACT_REQUESTS_FOR_ME
}