/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package at.fhooe.ecommunity.data.remote.openapi.cloud.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param contractId 
 * @param state 
 * @param addressContract 
 * @param addressProposer 
 * @param addressConsenter 
 * @param startEnergyData 
 * @param endEnergyData 
 * @param validityOfContract 
 * @param pricePerHour 
 * @param totalPrice 
 * @param dataUsage 
 * @param timeResolution 
 */

data class ConsentContractModel (

    @Json(name = "contractId")
    val contractId: kotlin.String? = null,

    @Json(name = "state")
    val state: kotlin.Int? = null,

    @Json(name = "addressContract")
    val addressContract: kotlin.String? = null,

    @Json(name = "addressProposer")
    val addressProposer: kotlin.String? = null,

    @Json(name = "addressConsenter")
    val addressConsenter: kotlin.String? = null,

    @Json(name = "startEnergyData")
    val startEnergyData: kotlin.String? = null,

    @Json(name = "endEnergyData")
    val endEnergyData: kotlin.String? = null,

    @Json(name = "validityOfContract")
    val validityOfContract: kotlin.String? = null,

    @Json(name = "pricePerHour")
    val pricePerHour: kotlin.String? = null,

    @Json(name = "totalPrice")
    val totalPrice: kotlin.String? = null,

    @Json(name = "dataUsage")
    val dataUsage: kotlin.String? = null,

    @Json(name = "timeResolution")
    val timeResolution: kotlin.String? = null

)

