/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package at.fhooe.ecommunity.data.remote.openapi.cloud.models

import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalBatterySystemDto
import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalChargeDto
import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalECommunityDto
import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalGridPriceRateDto
import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalMemberDto
import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalPVSystemDto
import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalSmartMeterDto
import at.fhooe.ecommunity.data.remote.openapi.cloud.models.LocalSupplierPriceRateDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param batterySystems 
 * @param charges 
 * @param eCommunity 
 * @param gridPriceRate 
 * @param member 
 * @param pvSystems 
 * @param smartMeter 
 * @param supplierPriceRate 
 */

data class LocalDto (

    @Json(name = "batterySystems")
    val batterySystems: kotlin.collections.List<LocalBatterySystemDto>? = null,

    @Json(name = "charges")
    val charges: kotlin.collections.List<LocalChargeDto>? = null,

    @Json(name = "eCommunity")
    val eCommunity: LocalECommunityDto? = null,

    @Json(name = "gridPriceRate")
    val gridPriceRate: LocalGridPriceRateDto? = null,

    @Json(name = "member")
    val member: LocalMemberDto? = null,

    @Json(name = "pvSystems")
    val pvSystems: kotlin.collections.List<LocalPVSystemDto>? = null,

    @Json(name = "smartMeter")
    val smartMeter: LocalSmartMeterDto? = null,

    @Json(name = "supplierPriceRate")
    val supplierPriceRate: LocalSupplierPriceRateDto? = null

)

