/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package at.fhooe.ecommunity.data.remote.openapi.cloud.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param baseRate 
 * @param workingPricePlus 
 * @param workingPriceMinus 
 * @param pricePerPeak 
 * @param taxRate 
 */

data class LocalSupplierPriceRateDto (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "baseRate")
    val baseRate: kotlin.Double? = null,

    @Json(name = "workingPricePlus")
    val workingPricePlus: kotlin.Double? = null,

    @Json(name = "workingPriceMinus")
    val workingPriceMinus: kotlin.Double? = null,

    @Json(name = "pricePerPeak")
    val pricePerPeak: kotlin.Double? = null,

    @Json(name = "taxRate")
    val taxRate: kotlin.Double? = null

)

