/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package at.fhooe.ecommunity.data.remote.openapi.cloud.models

import at.fhooe.ecommunity.data.remote.openapi.cloud.models.MinimalMemberDto

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param name 
 * @param members 
 */

data class MinimalECommunityDto (

    @Json(name = "id")
    val id: java.util.UUID? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "members")
    val members: kotlin.collections.List<MinimalMemberDto>? = null

)

