/**
 * e-community-cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package at.fhooe.ecommunity.data.remote.openapi.cloud.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param email 
 * @param userName 
 * @param password 
 * @param languageName 
 */

data class RegisterMemberModel (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "userName")
    val userName: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String,

    @Json(name = "languageName")
    val languageName: kotlin.String

)

