/**
 * e-community-local
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package local.org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param aesKey 
 * @param apiKey 
 * @param name 
 * @param description 
 * @param isMain 
 * @param measuresConsumption 
 * @param measuresFeedIn 
 * @param isDirectFeedIn 
 * @param isOverflowFeedIn 
 */

data class SmartMeterModel (

    @Json(name = "id")
    var id: java.util.UUID? = null,

    @Json(name = "aesKey")
    var aesKey: kotlin.String? = null,

    @Json(name = "apiKey")
    var apiKey: kotlin.String? = null,

    @Json(name = "name")
    var name: kotlin.String? = null,

    @Json(name = "description")
    var description: kotlin.String? = null,

    @Json(name = "isMain")
    var isMain: kotlin.Boolean? = null,

    @Json(name = "measuresConsumption")
    var measuresConsumption: kotlin.Boolean? = null,

    @Json(name = "measuresFeedIn")
    var measuresFeedIn: kotlin.Boolean? = null,

    @Json(name = "isDirectFeedIn")
    var isDirectFeedIn: kotlin.Boolean? = null,

    @Json(name = "isOverflowFeedIn")
    var isOverflowFeedIn: kotlin.Boolean? = null

)

