/**
 * e-community-local
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package local.org.openapitools.client.models


import com.squareup.moshi.Json

/**
 *
 *
 * @param memberId
 * @param isConnectedToInternet
 * @param isWiredConnected
 * @param wifiSSID
 */

data class StatusDto (

    @Json(name = "memberId")
    val memberId: java.util.UUID? = null,

    @Json(name = "isConnectedToInternet")
    val isConnectedToInternet: kotlin.Boolean? = null,

    @Json(name = "isWiredConnected")
    val isWiredConnected: kotlin.Boolean? = null,

    @Json(name = "wifiSSID")
    val wifiSSID: kotlin.String? = null,

    @Json(name = "smartMeter")
    val smartMeter: SmartMeterModel? = null
)

